
package com.chr.client.code2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpWebService", targetNamespace = "http://service.web.server.chr.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmp", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.UpdateEmp")
    @ResponseWrapper(localName = "updateEmpResponse", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.UpdateEmpResponse")
    public void updateEmp(
            @WebParam(name = "arg0", targetNamespace = "")
                    Emp arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEmp", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.DeleteEmp")
    @ResponseWrapper(localName = "deleteEmpResponse", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.DeleteEmpResponse")
    public void deleteEmp(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "insertEmp", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.InsertEmp")
    @ResponseWrapper(localName = "insertEmpResponse", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.InsertEmpResponse")
    public void insertEmp(
            @WebParam(name = "arg0", targetNamespace = "")
                    Emp arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.chr.client.code2.Emp>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectAll", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.SelectAll")
    @ResponseWrapper(localName = "selectAllResponse", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.SelectAllResponse")
    public List<Emp> selectAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.chr.client.code2.Emp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectOne", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.SelectOne")
    @ResponseWrapper(localName = "selectOneResponse", targetNamespace = "http://service.web.server.chr.com/", className = "com.chr.client.code2.SelectOneResponse")
    public Emp selectOne(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
