
package com.chr.client.code;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpWebService", targetNamespace = "http://webservice.hhb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.UpdateResponse")
    public String update(
            @WebParam(name = "arg0", targetNamespace = "")
                    Emp arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.chr.client.code.Emp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOne", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.FindOne")
    @ResponseWrapper(localName = "findOneResponse", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.FindOneResponse")
    public Emp findOne(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.SaveResponse")
    public String save(
            @WebParam(name = "arg0", targetNamespace = "")
                    Emp arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.DeleteResponse")
    public String delete(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.chr.client.code.Emp>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://webservice.hhb.com/", className = "com.chr.client.code.FindAllResponse")
    public List<Emp> findAll();

}
