server:
  context-path: /ems_pink
  port: 8888
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/chr/mapper/*
  type-aliases-package: com.chr.entity